# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany_rel', '0002_auto_20151101_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='manytomany_rel_articlepluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='pluginmodelwithfkfrommodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='manytomany_rel_pluginmodelwithfkfrommodel', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='pluginmodelwithm2mtomodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='manytomany_rel_pluginmodelwithm2mtomodel', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
