# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='meta_testpluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='testpluginmodel2',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='meta_testpluginmodel2', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='testpluginmodel4',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='meta_testpluginmodel4', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
