# Generated by Django 5.2.9 on 2026-02-18 11:22

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("cms", "0001_initial"),
        ("cms", "0002_auto_20140816_1918"),
        ("cms", "0003_auto_20140926_2347"),
        ("cms", "0004_auto_20140924_1038"),
        ("cms", "0005_auto_20140924_1039"),
        ("cms", "0006_auto_20140924_1110"),
        ("cms", "0007_auto_20141028_1559"),
        ("cms", "0008_auto_20150208_2149"),
        ("cms", "0008_auto_20150121_0059"),
        ("cms", "0009_merge"),
        ("cms", "0010_migrate_use_structure"),
        ("cms", "0011_auto_20150419_1006"),
        ("cms", "0012_auto_20150607_2207"),
        ("cms", "0013_urlconfrevision"),
        ("cms", "0014_auto_20160404_1908"),
        ("cms", "0015_auto_20160421_0000"),
        ("cms", "0016_auto_20160608_1535"),
        ("cms", "0017_pagetype"),
        ("cms", "0018_create_pagenode"),
        ("cms", "0019_set_pagenode"),
        ("cms", "0020_old_tree_cleanup"),
        ("cms", "0021_auto_20180507_1432"),
        ("cms", "0022_auto_20180620_1551"),
    ]

    dependencies = [
        ("auth", "__first__"),
        ("sites", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Placeholder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slot", models.CharField(db_index=True, editable=False, max_length=255, verbose_name="slot")),
                ("default_width", models.PositiveSmallIntegerField(editable=False, null=True, verbose_name="width")),
            ],
            options={
                "permissions": (("use_structure", "Can use Structure mode"),),
            },
        ),
        migrations.CreateModel(
            name="TreeNode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.treenode",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="djangocms_nodes",
                        to="sites.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "ordering": ("path",),
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cms_pages", to="cms.treenode"
                    ),
                ),
                ("created_by", models.CharField(editable=False, max_length=255, verbose_name="created by")),
                ("changed_by", models.CharField(editable=False, max_length=255, verbose_name="changed by")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("changed_date", models.DateTimeField(auto_now=True)),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='When the page should go live. Status must be "Published" for page to go live.',
                        null=True,
                        verbose_name="publication date",
                    ),
                ),
                (
                    "publication_end_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When to expire the page. Leave empty to never expire.",
                        null=True,
                        verbose_name="publication end date",
                    ),
                ),
                ("in_navigation", models.BooleanField(db_index=True, default=True, verbose_name="in navigation")),
                (
                    "soft_root",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="All ancestors will not be displayed in the navigation",
                        verbose_name="soft root",
                    ),
                ),
                (
                    "reverse_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="A unique identifier that is used with the page_url templatetag for linking to this page",
                        max_length=40,
                        null=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "navigation_extenders",
                    models.CharField(
                        blank=True, db_index=True, max_length=80, null=True, verbose_name="attached menu"
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("bootstrap5/base.html", "Standard"),
                            ("base.html", "Test"),
                            ("INHERIT", "Inherit the template of the nearest ancestor"),
                        ],
                        default="INHERIT",
                        help_text="The template used to render the content.",
                        max_length=100,
                        verbose_name="template",
                    ),
                ),
                ("login_required", models.BooleanField(default=False, verbose_name="login required")),
                (
                    "limit_visibility_in_menu",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (None, "no limit set"),
                            (1, "for logged in users only"),
                            (2, "for anonymous users only"),
                        ],
                        db_index=True,
                        default=None,
                        help_text="limit when this page is visible in the menu",
                        null=True,
                        verbose_name="menu visibility",
                    ),
                ),
                ("is_home", models.BooleanField(db_index=True, default=False, editable=False)),
                (
                    "application_urls",
                    models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name="application"),
                ),
                (
                    "application_namespace",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="application instance name"),
                ),
                ("publisher_is_draft", models.BooleanField(db_index=True, default=True, editable=False)),
                ("languages", models.CharField(blank=True, editable=False, max_length=255, null=True)),
                (
                    "xframe_options",
                    models.IntegerField(
                        choices=[(0, "Inherit from parent page"), (1, "Deny"), (2, "Only this website"), (3, "Allow")],
                        default=0,
                    ),
                ),
                (
                    "publisher_public",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_draft",
                        to="cms.page",
                    ),
                ),
                ("placeholders", models.ManyToManyField(editable=False, to="cms.placeholder")),
                ("is_page_type", models.BooleanField(default=False)),
            ],
            options={
                "permissions": (
                    ("view_page", "Can view page"),
                    ("publish_page", "Can publish page"),
                    ("edit_static_placeholder", "Can edit static placeholders"),
                ),
                "verbose_name": "page",
                "verbose_name_plural": "pages",
            },
        ),
        migrations.CreateModel(
            name="CMSPlugin",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveSmallIntegerField(default=0, editable=False, verbose_name="position")),
                ("language", models.CharField(db_index=True, editable=False, max_length=15, verbose_name="language")),
                (
                    "plugin_type",
                    models.CharField(db_index=True, editable=False, max_length=50, verbose_name="plugin_name"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="creation date"
                    ),
                ),
                ("changed_date", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "placeholder",
                    models.ForeignKey(
                        editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to="cms.placeholder"
                    ),
                ),
                ("depth", models.PositiveIntegerField(editable=False)),
                ("numchild", models.PositiveIntegerField(default=0, editable=False)),
                ("path", models.CharField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GlobalPagePermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("can_change", models.BooleanField(default=True, verbose_name="can edit")),
                ("can_add", models.BooleanField(default=True, verbose_name="can add")),
                ("can_delete", models.BooleanField(default=True, verbose_name="can delete")),
                (
                    "can_change_advanced_settings",
                    models.BooleanField(default=False, verbose_name="can change advanced settings"),
                ),
                ("can_publish", models.BooleanField(default=True, verbose_name="can publish")),
                (
                    "can_change_permissions",
                    models.BooleanField(
                        default=False, help_text="on page level", verbose_name="can change permissions"
                    ),
                ),
                ("can_move_page", models.BooleanField(default=True, verbose_name="can move")),
                (
                    "can_view",
                    models.BooleanField(
                        default=False, help_text="frontend view restriction", verbose_name="view restricted"
                    ),
                ),
                (
                    "can_recover_page",
                    models.BooleanField(
                        default=True, help_text="can recover any deleted page", verbose_name="can recover pages"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If none selected, user haves granted permissions to all sites.",
                        to="sites.site",
                        verbose_name="sites",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page global permission",
                "verbose_name_plural": "Pages global permissions",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("fr", "French"),
                            ("zh", "Chinese"),
                        ],
                        help_text="The language for the admin interface and toolbar",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "clipboard",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.placeholder",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="djangocms_usersettings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user setting",
                "verbose_name_plural": "user settings",
            },
        ),
        migrations.CreateModel(
            name="UrlconfRevision",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revision", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PageUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User (page)",
                "verbose_name_plural": "Users (page)",
            },
            bases=("auth.user",),
        ),
        migrations.CreateModel(
            name="AliasPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cms_aliasplugin",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alias_reference",
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "alias_placeholder",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alias_placeholder",
                        to="cms.placeholder",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="PlaceholderReference",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cms_placeholderreference",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "placeholder_ref",
                    models.ForeignKey(
                        editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cms.placeholder"
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="PageType",
            fields=[],
            options={
                "default_permissions": [],
                "proxy": True,
            },
            bases=("cms.page",),
        ),
        migrations.CreateModel(
            name="StaticPlaceholder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descriptive name to identify this static placeholder. Not displayed to users.",
                        max_length=255,
                        verbose_name="static placeholder name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="To render the static placeholder in templates.",
                        max_length=255,
                        verbose_name="placeholder code",
                    ),
                ),
                ("dirty", models.BooleanField(default=False, editable=False)),
                (
                    "creation_method",
                    models.CharField(
                        blank=True,
                        choices=[("template", "by template"), ("code", "by code")],
                        default="code",
                        max_length=20,
                        verbose_name="creation_method",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="static_draft",
                        to="cms.placeholder",
                        verbose_name="placeholder content",
                    ),
                ),
                (
                    "public",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="static_public",
                        to="cms.placeholder",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "static placeholder",
                "verbose_name_plural": "static placeholders",
                "unique_together": {("code", "site")},
            },
        ),
        migrations.CreateModel(
            name="PageUserGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_usergroups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User group (page)",
                "verbose_name_plural": "User groups (page)",
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="PagePermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("can_change", models.BooleanField(default=True, verbose_name="can edit")),
                ("can_add", models.BooleanField(default=True, verbose_name="can add")),
                ("can_delete", models.BooleanField(default=True, verbose_name="can delete")),
                (
                    "can_change_advanced_settings",
                    models.BooleanField(default=False, verbose_name="can change advanced settings"),
                ),
                ("can_publish", models.BooleanField(default=True, verbose_name="can publish")),
                (
                    "can_change_permissions",
                    models.BooleanField(
                        default=False, help_text="on page level", verbose_name="can change permissions"
                    ),
                ),
                ("can_move_page", models.BooleanField(default=True, verbose_name="can move")),
                (
                    "can_view",
                    models.BooleanField(
                        default=False, help_text="frontend view restriction", verbose_name="view restricted"
                    ),
                ),
                (
                    "grant_on",
                    models.IntegerField(
                        choices=[
                            (1, "Current page"),
                            (2, "Page children (immediate)"),
                            (3, "Page and children (immediate)"),
                            (4, "Page descendants"),
                            (5, "Page and descendants"),
                        ],
                        default=5,
                        verbose_name="Grant on",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.page",
                        verbose_name="page",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page permission",
                "verbose_name_plural": "Page permissions",
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.CharField(db_index=True, max_length=15, verbose_name="language")),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="A description of the page used by search engines.",
                        null=True,
                        verbose_name="Description meta tag",
                    ),
                ),
                ("title", models.CharField(help_text="The default title", max_length=255, verbose_name="title")),
                (
                    "page_title",
                    models.CharField(
                        blank=True,
                        help_text="Overwrites what is displayed at the top of your browser or in bookmarks",
                        max_length=255,
                        null=True,
                        verbose_name="Page Title",
                    ),
                ),
                (
                    "menu_title",
                    models.CharField(
                        blank=True,
                        help_text="Overwrite what is displayed in the menu",
                        max_length=255,
                        null=True,
                        verbose_name="Menu Title",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, verbose_name="slug")),
                ("path", models.CharField(db_index=True, max_length=255, verbose_name="Path")),
                (
                    "has_url_overwrite",
                    models.BooleanField(
                        db_index=True, default=False, editable=False, verbose_name="has url overwrite"
                    ),
                ),
                (
                    "redirect",
                    models.CharField(
                        blank=True,
                        help_text="Redirects to this URL.",
                        max_length=2048,
                        null=True,
                        verbose_name="redirect",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="creation date"
                    ),
                ),
                ("published", models.BooleanField(default=False, verbose_name="is published")),
                ("publisher_is_draft", models.BooleanField(db_index=True, default=True, editable=False)),
                ("publisher_state", models.SmallIntegerField(db_index=True, default=0, editable=False)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title_set",
                        to="cms.page",
                        verbose_name="page",
                    ),
                ),
                (
                    "publisher_public",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_draft",
                        to="cms.title",
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "page")},
            },
        ),
        migrations.AlterModelOptions(
            name="page",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (
                    ("view_page", "Can view page"),
                    ("publish_page", "Can publish page"),
                    ("edit_static_placeholder", "Can edit static placeholders"),
                ),
                "verbose_name": "page",
                "verbose_name_plural": "pages",
            },
        ),
    ]
