# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20180507_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='path',
            new_name='path_override',
        ),
    ]
