# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20180507_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='path_override',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Path'),
        ),
    ]
