# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_title_placeholders'),
    ]

    operations = [
    ]
