# Generated by Django 2.1a1 on 2018-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180604_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='published',
            field=models.BooleanField(blank=True, default=False, verbose_name='is published'),
        ),
    ]
