# Generated by Django 2.1.1 on 2018-09-03 12:39

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPageOnDeleteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='on delete test', max_length=50)),
                ('page', cms.models.fields.PageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page')),
            ],
        ),
    ]
