# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_title_path_overide_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='has_url_overwrite',
        ),
        migrations.RemoveField(
            model_name='title',
            name='path',
        ),
    ]
