# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 14:26
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Page = apps.get_model('cms', 'Page')
    for page in Page.objects.using(db_alias):
        page.title_set.update(
            created_by=page.created_by,
            changed_by=page.changed_by,
            changed_date=page.changed_date,
            in_navigation=page.in_navigation,
            limit_visibility_in_menu=page.limit_visibility_in_menu,
            template=page.template,
            xframe_options=page.xframe_options,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_create_title_fields_to_be_moved_from_page'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
