# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 14:26
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Page = apps.get_model('cms', 'Page')

    page_qs = Page.objects.using(db_alias)
    cms_pages = page_qs.prefetch_related('title_set')
    for page in cms_pages:
        for title in page.title_set.all():
            title.created_by = page.created_by
            title.changed_by = page.changed_by
            title.changed_date = page.changed_date
            title.in_navigation = page.in_navigation
            title.limit_visibility_in_menu = page.limit_visibility_in_menu
            title.template = page.template
            title.xframe_options = page.xframe_options
            title.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_create_title_fields_to_be_moved_from_page'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
