# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_migrate_fields_from_page_to_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='template',
        ),
        migrations.RemoveField(
            model_name='page',
            name='xframe_options',
        ),
        migrations.RemoveField(
            model_name='page',
            name='in_navigation',
        ),
        migrations.RemoveField(
            model_name='page',
            name='soft_root',
        ),
        migrations.RemoveField(
            model_name='page',
            name='limit_visibility_in_menu',
        ),
    ]
