# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 15:39
from __future__ import unicode_literals

import cms.models.fields
import cms.test_utils.project.placeholderapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_migrate_fields_from_page_to_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='template',
        ),
        migrations.RemoveField(
            model_name='page',
            name='xframe_options',
        ),
        migrations.RemoveField(
            model_name='page',
            name='in_navigation',
        ),
        migrations.RemoveField(
            model_name='page',
            name='soft_root',
        ),
        migrations.RemoveField(
            model_name='page',
            name='limit_visibility_in_menu',
        ),
        migrations.AlterField(
            model_name='title',
            name='changed_by',
            field=models.CharField(editable=False, max_length=255, verbose_name='changed by'),
        ),
        migrations.AlterField(
            model_name='title',
            name='created_by',
            field=models.CharField(editable=False, max_length=255, verbose_name='created by'),
        ),
    ]
