# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_remove_page_fields'),
    ]

    operations = [
        migrations.RenameModel('Title', 'PageContent'),
    ]
