# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 12:39
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Title = apps.get_model('cms', 'Title')
    title_ct = ContentType.objects.get_for_model(Title)

    for title in Title.objects.using(db_alias):
        title.placeholders.update(
            content_type=title_ct,
            object_id=title.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_remove_fields'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
