# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_remove_title_to_pagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagecontent_set', to='cms.Page', verbose_name='page'),
        ),
    ]
