# Generated by Django 3.2.23 on 2024-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_page', 'Can view page'), ('publish_page', 'Can publish page'), ('edit_static_placeholder', 'Can edit static placeholders')), 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AddField(
            model_name='globalpagepermission',
            name='can_publish',
            field=models.BooleanField(default=True, verbose_name='can publish'),
        ),
        migrations.AddField(
            model_name='pagepermission',
            name='can_publish',
            field=models.BooleanField(default=True, verbose_name='can publish'),
        ),
    ]
