# Generated by Django 4.1.10 on 2024-01-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placeholder',
            unique_together={('content_type', 'object_id', 'slot')},
        ),
    ]
