# Generated by Django 4.1.10 on 2023-10-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_alter_cmsplugin_id_alter_globalpagepermission_id_and_more'),
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
    ]
