# Generated by Django 4.1.13 on 2024-03-04 14:25

from django.db import migrations, models
from django.db.models.aggregates import Count, Max


def forwards(apps, schema_editor):
    PageUrl = apps.get_model('cms', 'PageUrl')
    duplicates = PageUrl.objects.values('path', 'language') \
        .order_by('path', 'language') \
        .annotate(max_id=Max('id'), count_id=Count('id')) \
        .filter(count_id__gt=1)
    print("\n")
    for duplicate in duplicates:
        print("Deleting duplicate ({language}, {path})".format(**duplicate))
        PageUrl.objects.filter(
            language=duplicate['language'],
            path=duplicate['path'],
        ).exclude(
            id=duplicate['max_id'],
        ).delete()

    duplicates = PageUrl.objects.values('page_id', 'language') \
        .order_by('page_id', 'language') \
        .annotate(max_id=Max('id'), count_id=Count('id')) \
        .filter(count_id__gt=1)
    print("\n")
    for duplicate in duplicates:
        print("Deleting duplicate ({language}, {page_id})".format(**duplicate))
        PageUrl.objects.filter(
            language=duplicate['language'],
            page_id=duplicate['page_id'],
        ).exclude(
            id=duplicate['max_id']
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_alter_placeholder_unique_together'),
    ]


    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='pageurl',
            unique_together={('page', 'language'), ('path', 'language')},
        ),
    ]
