# Generated by Django 4.2.13 on 2024-06-21 14:55

from django.db import migrations, models
import django.db.models.deletion

import cms.models.settingmodels


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cms', '0037_merge_page_treenode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_pages', to='sites.site', verbose_name='site'),
        ),
        migrations.RenameField(
            model_name='page',
            old_name='node',
            new_name='node_deprecated',
        ),
        migrations.AlterField(
            model_name='page',
            name='node_deprecated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_pages', to='cms.treenode'),
        ),
        migrations.RemoveField(
            model_name='page',
            name='node_deprecated',
        ),
        migrations.DeleteModel(
            name='TreeNode',
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="clipboard",
            field=cms.models.settingmodels.PlaceholderForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cms.placeholder",
            ),
        ),
    ]
