# Generated by Django 4.2.13 on 2024-07-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_wip_uniweb'),
        ('cms', '0038_alter_page_site'),
    ]

    operations = [
    ]
