# Generated by Django 4.1.13 on 2024-05-02 09:29

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_pageurl_unique_together_path_page_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageurl',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pageurl',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('path'), models.F('language'), name='unique_together_path_language'),
        ),
        migrations.AddConstraint(
            model_name='pageurl',
            constraint=models.UniqueConstraint(fields=('page', 'language'), name='unique_together_page_language'),
        ),
        migrations.AlterUniqueTogether(
            name='placeholder',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='placeholder',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'slot'), name='cms_placeholder_unique'),
        ),
    ]
