# Generated by Django 4.2.16 on 2024-11-14 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0038_alter_page_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="languages",
        ),
        migrations.AlterUniqueTogether(
            name="pageurl",
            unique_together={("language", "page")},
        ),
    ]
