# Generated by Django 4.1.13 on 2024-05-06 14:39

from django.db import migrations, models
import django.db.models.functions.text
from django.db.models import F, Q
from django.db.models.functions import Lower


def forwards(apps, schema_editor):
    PageUrl = apps.get_model('cms', 'PageUrl')
    qs = PageUrl.objects.exclude(slug=Lower(F('slug')))
    qs.update(slug=Lower(F('slug')))


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_alter_pageurl_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='pageurl',
            constraint=models.CheckConstraint(check=models.Q(('slug', django.db.models.functions.text.Lower(models.F('slug')))), name='check_slug_lowercase'),
        ),
    ]
