# Generated by Django 6.0.dev20250402072445 on 2025-04-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_alter_pageuser_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageurl',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pageurl',
            constraint=models.UniqueConstraint(fields=('path', 'language'), name='unique_together_path_language'),
        ),
        migrations.AddConstraint(
            model_name='pageurl',
            constraint=models.UniqueConstraint(fields=('page', 'language'), name='unique_together_page_language'),
        ),
    ]
