# Generated by Django 6.0.dev20250402084405 on 2025-04-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_alter_pageuser_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageurl',
            unique_together=set(),
        ),
    ]
