# Generated by Django 6.0.dev20250402085059 on 2025-04-04 11:35

import django.db.models.deletion
from django.db import migrations, models

def set_site_from_page(apps, schema_editor):
    PageUrl = apps.get_model('cms', 'PageUrl')
    for url in PageUrl.objects.all():
        url.site = url.page.site
        url.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_alter_pageuser_created_by_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageurl',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pageurl',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='pageurl',
            constraint=models.UniqueConstraint(condition=models.Q(('path__isnull', False)), fields=('path', 'language', 'site'), name='unique_together_path_language_site'),
        ),
        migrations.AddConstraint(
            model_name='pageurl',
            constraint=models.UniqueConstraint(fields=('page', 'language'), name='unique_together_page_language'),
        ),
        migrations.RunPython(set_site_from_page),
    ]
