# Generated by Django 5.2.1.dev20250424131232 on 2025-05-12 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placeholderreference",
            name="placeholder_ref",
        ),
        migrations.DeleteModel(
            name="StaticPlaceholder",
        ),
    ]
