# -*- coding: utf-8 -*-

from cms.tests.static_analysis import *  # nopyflakes
from cms.tests.alias import *  # nopyflakes
from cms.tests.admin import *  # nopyflakes
from cms.tests.api import *  # nopyflakes
from cms.tests.apphooks import *  # nopyflakes
from cms.tests.docs import *  # nopyflakes
from cms.tests.extensions import *  # nopyflakes
from cms.tests.forms import *  # nopyflakes
from cms.tests.i18n import *  # nopyflakes
from cms.tests.mail import *  # nopyflakes
from cms.tests.menu import *  # nopyflakes
from cms.tests.menu_utils import *  # nopyflakes
from cms.tests.multilingual import *  # nopyflakes
from cms.tests.navextender import *  # nopyflakes
from cms.tests.nonroot import *  # nopyflakes
from cms.tests.page import *  # nopyflakes
from cms.tests.permissions import *  # nopyflakes
from cms.tests.permmod import *  # nopyflakes
from cms.tests.placeholder import *  # nopyflakes
from cms.tests.plugins import *  # nopyflakes
from cms.tests.po import *  # nopyflakes
from cms.tests.publisher import *  # nopyflakes
from cms.tests.rendering import *  # nopyflakes
from cms.tests.reversion_tests import *  # nopyflakes
from cms.tests.security import *  # nopyflakes
from cms.tests.settings import *  # nopyflakes
from cms.tests.site import *  # nopyflakes
from cms.tests.sitemap import *  # nopyflakes
from cms.tests.static_placeholder import *  # nopyflakes
from cms.tests.staticfiles import *  # nopyflakes
from cms.tests.templatetags import *  # nopyflakes
from cms.tests.templates import *  # nopyflakes
from cms.tests.toolbar import *  # nopyflakes
from cms.tests.toolbar_pool import *  # nopyflakes
from cms.tests.urlutils import *  # nopyflakes
from cms.tests.views import *  # nopyflakes
from cms.tests.management import *  # nopyflakes
from cms.tests.fixture_loading import *  # nopyflakes
from cms.tests.menu_page_viewperm import *  # nopyflakes
from cms.tests.menu_page_viewperm_staff import *  # nopyflakes
from cms.tests.nested_plugins import *  # nopyflakes
from cms.tests.check import *  # nopyflakes
from cms.tests.frontend import *  # nopyflakes
from cms.tests.signals import *  # nopyflakes
from cms.tests.no_i18n import *  # nopyflakes
from cms.tests.cache import *  # nopyflakes
