# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeholderapp', '0005_example1_decimal_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multilingualexample1translation',
            options={'default_permissions': (), 'managed': True},
        ),
    ]
