# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bunch_of_plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplugin1',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bunch_of_plugins_testplugin1', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='testplugin2',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bunch_of_plugins_testplugin2', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
