BBBBBBB BBBBBBBBBBBBB
 _('Index') 
BBBBB BBBB

   XXX XXXXXXXXXXX _('Index') XXXXX

   XXX _('Index pages by letter') XXXXX

   XXXBBB BBBB BBBBB BB BBBBBBBBBBBBBBB B
   XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     BB BBB BBBBBBBBBX BBBBB
   B BBBBBBXXXX

   XXXXX XXXXXXXXXXXXXXXX _('Full index on one page') XXXXXXXXX
                                               X _('can be huge') XXXXXXXXX

BBBBBBBB

BBBBB BBBBBBBBBB
BB BBBBBBBBBBB
   XXXXXXXXXXXXXX
   XXXBBB BBBB BBBBB BB BBBBBBBBBBBBBBB B
   XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     BB BBB BBBBBBBBBX BBBBB
   B BBBBBBXXXX

   XXXXX XXXXXXXXXXXXXXXX _('Full index on one page') XXXXXXXXXXXXXXXXX
BBBBB
   
BBBBBBBB
