B BBBBB BBBBBBB B
XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
B BBBBBBBB
B BBB BBBBBBBBB B BBBBBBBBB BB BBB BBBBBBB BBB B BBBBBBBB BB BBBBBBBBB
B BBB BBBBBBBBB B BBBBBBBBB BB BBB BBBBBBB BBB B BB BB BBBBBBBBB

B BBBBB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXX
      XXXX _('Navigation') XXXXX
      XXXX
        B BBB BBBBBBB BB BBBBBBBB
        XXX XXXXXXXXXXXXX BB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBX
          XX XXXXXXX XXXXXXXFFFFFFFFFX
             XXXXX
          B BB BBB BBBBBBBBBBBBBBBXXXXX
        B BBBBBB
        B BBBBB BBBBBBBBBBB
        XXXXXX XXXXXXXXFXXXXXXXXX
        B BBBBBBBB
        B BBB BBBBBB BB BBBBBBB
          XXXXXX XXXXXXFX BB BBBBBBBBBBBBBBXXXXXXXXXX
        B BBBBBB
        B BBBBB BBBBBBBBBBB BBBBBBBB
      XXXXX
    XXXXXX
B BBBBBBBB

B BBBBB BBBBBBBBB
      B BB BBB BBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          B BBBBB BBBBBBBBBBB
          B BB BBBB
            XX XXXXXXXXXXXXXXX XXXXXXXX
              XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
            XXXXXXXX
          B BBBBB
          B BBBBBBBB
          B BBBBB BBBBBBBBBB
          B BB BBBBBBBBBBB
            XXXXXX XXXXXXXX _('Table Of Contents') XXXXXXXXX
            
          B BBBBB
          B BBBBBBBB
          B BBBBB BBBBBBBBBB
          B BB BBBB
            XXXX _('Previous topic') XXXXX
            XX XXXXXXXXXXXXXXXXXX XXXXXXFX
                                  XXXXXXX _('previous chapter') XXXXXXXXXX
          B BBBBB
          B BB BBBB
            XXXX _('Next topic') XXXXX
            XX XXXXXXXXXXXXXXXXXX XXXXXXFX
                                  XXXXXXX _('next chapter') XXXXXXXXXX
          B BBBBB
          B BBBBBBBB
          B BBBBB BBBBBBBBBBBBBBBBB
          B BB BBBBBBBBBBB BBB BBBBBBBBBB BBB BBBBBBBBBB
            XXXX _('This Page') XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXFX
                     XXXXXXXXXXXXXXX _('Show Source') XXXXXXXXX
            XXXXX
          B BBBBB
          B BBBBBBBB
          B BB BBBBBBBBBBBBB
          BBBBBBB BBBBBBBBBBBBB
          B BBBBB
          B BBBBB BBBBBBBBBBBBB
          B BB BBBBBBBB BB BBBBBBBB
          XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX _('Quick search') XXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XX
                XXXXXX XXXXXXXXXXXXX XXXXXXX _('Go') X XX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XX
              XXXXXXX
              XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX
               _('Enter search terms or a module, class or function name.') 
              XXXX
          XXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          B BBBBB
          B BBBBBBBB
        XXXXXX
      XXXXXX
      B BBBBBBBBBB
B BBBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX
    
    B BB BBB BBBBBBBB
      B BBB BBBBBBBBBBB B B BBBBBBB BBBBBB B BBBBBBBBBBB
    B BBBB
      B BBB BBBBBBBBBBB B BB
    B BBBBB
    XXXXXXXFFFFFFFFFXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XX
    B BB BBB BBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXXX    XXX
        XXXXXXXX     XFXX
        XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXX XXX
        XXXXXXXXXXX  FFFFF
      XX
    XXXXXXXXX
    B BBB BBBBBBBBBB BB BBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    B BBBBBB
    B BB BBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXX BBBBBBBBX
          XXXXXXXXX
    B BBBBB
    B BB BBBBBBB
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXX
    B BBBBB
    B BBBBB
B BBBBB BBBBBBBB
    B BB BBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXX XXXXXXX _('About these documents') X XXXXXXX XX
    B BBBBB
    B BB BBBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXX XXXXXXX _('Index') X XXXXXXX XX
    B BBBBB
    B BB BBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXX XXXXXXX _('Search') X XXXXXXX XX
    B BBBBB
    B BB BBBBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXX XXXXXXX _('Copyright') X XXXXXXX XX
    B BBBBB
    XXXXX XXXXXXXXX XXXXXXXFX XXXXXXX XX
    B BB BBBBBBB
    XXXXX XXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXFX XX
    B BBBBB
    B BB BBBB
    XXXXX XXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXFX XX
    B BBBBB
    B BB BBBB
    XXXXX XXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXFX XX
    B BBBBB
B BBBBBBBB
B BBBBB BBBBBBBBB BBBBBBBB
  XXXXXXX
  XXXXXX
B BBBBB BBBBBBBBBBBBBB

B BBBBB BBBBBBBBBBBBBBB

B BBBBB BBBBBBBB  BBBBBBBB

    XXXX XXXXXXXXXXXXXXXXX
B BBBBB BBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      B BB BBB BBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXX
      B BBBBBBBBBB
          XXXX XXXXXXXXXXXXX
            BBBBB BBBB BBBBBBBB
          XXXXXX
      B BB BBB BBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      B BBBBBBBBBB
      XXXXXX
B BBBBBBBB

B BBBBB BBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

B BBBBB BBBBBBBBBBBBBBB

B BBBBB BBBBBB
    XXXX XXXXXXXXXXXXXXX
    B BB BBBBBBBBBBBBBBBBBBB
      BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XBBBBBBBB
    B BBBB
      BBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXX XBBBBBBBB
    B BBBBB
    B BB BBBBBBBBBBBB
      BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXX XX XBBBBBBBB
    B BBBBB
    B BB BBBBBBBBBBB
      BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XBBBBBBBB
    B BBBBB
    XXXXXX
B BBBBBBBB
  XXXXXXX
XXXXXXX
