BBBBBBB BBBBBBBBBBBBB
 _('Search') 
BBB BBBBBBBBBBBB B BBBBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBB
  XXX XXXXXXXXXXXXXXXXXXXXXXXXXX _('Search') XXXXX
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX
    BBBBBXXXXXX XXXXXXXX XXXXXXXXXX XX XXXXXX XXX XXXXXX
    XXXXXXXXXXXXXXBBBBBBBB
  XXXX
  XXXXXX
  XXX
    BBBBBXXXX XXXX XXX XXX XXXXXX XXXXX XXXXXXXXXX XXXXX XXXX XXXXXX
    XXXXX XXXX XXX XXX XXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXX XXXXXX
    XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXX XXX XXX XX XXX XXXXXX XXXXX
    XXXXXXXXXX XXXXX XXXXX XXXXX XXXXXX XX XXX XXXXXX XXXXXBBBBBBBB
  XXXX
  XXXXX XXXXXXXXX XXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXX _('search') X XX
    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXX
  BB BBBBBBBBBBBBBBBB
    XXXX _('Search Results') XXXXX
    BB BBB BBBBBBBBBBBBBB
      XXX _('Your search did not match any results.') XXXX
    BBBBB
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX
  BB BBBBBBBBBBBBBB
    XXXX
    BBB BBBBB BBBBBBBB BBBBBBB BB BBBBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXFXXXXXX
      XXXXX
    BBBBBB
    XXXXX
  BBBBB
  XXXXXX
BBBBBBBB
BBBBB BBBBBB
  
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
