#!/bin/bash

# This script will take the last CHANGELOG.rst, pull information from the commit logs since last tagged version
# and update the content to create dedicated sections

# Scope used in this script
declare -A SCOPES_HEADINGS
declare -a SCOPES

SCOPES=("feat" "security" "fix" "style" "refactor" "tools")
SCOPES_HEADINGS["feat"]="Features:"
SCOPES_HEADINGS["fix"]="Bug Fixes:"
SCOPES_HEADINGS["security"]="Security Updates:"
SCOPES_HEADINGS["style"]="Styles:"
SCOPES_HEADINGS["refactor"]="Refactoring and Cleanups:"
SCOPES_HEADINGS["tools"]="Internal Tools:"


# argument checks

if [ -z "$1" ] ; then
    echo "Usage $0 <version> [base_version]"
    echo
    echo "Update the CHANGELOG.rst to create <version>"
    echo "Version can be X.Y.Zsuffix"
    echo "suffix can be rc, or anything, X,Y,Z are numbers"
    exit 1
fi

FULL_VERSION="$1"

# extracting version from the FULL_VERSION, and sanity checks
if ! echo "$FULL_VERSION" | grep -q "^\([0-9]\+\.\)\{2\}[0-9]\+"; then
    echo "Incorrect version format, must be X.Y.Z[suffix]"
    exit 1
fi

# shellcheck disable=SC2001
VERSUFFIX=$(echo "${FULL_VERSION}" | sed -e "s/^\(\([0-9]\+\.\)\{2\}[0-9]\+\)//")

# shellcheck disable=SC2001
VERSION=$(echo "${FULL_VERSION}" | sed -e "s/${VERSUFFIX}\$//")

# extracting the base version from changelog
OLD_FULL_VERSION="$2"
if [ -z "${OLD_FULL_VERSION}" ]; then
    OLD_FULL_VERSION=$(grep -vi "unreleased\|unpublished" CHANGELOG.rst | awk '/^[0-9]+\.[0-9]+\.[0-9] / { print $1; nextfile }')
else
    if ! echo "$OLD_FULL_VERSION" | grep -q "^\([0-9]\+\.\)\{2\}[0-9]\+"; then
        echo "base version incorrect format, must be X.Y.Z"
        exit 1
    fi
fi

# shellcheck disable=SC2001
OLD_VERSUFFIX=$(echo "${OLD_FULL_VERSION}" | sed -e "s/^\(\([0-9]\+\.\)\{2\}[0-9]\+\)//")

# shellcheck disable=SC2001
OLD_VERSION=$(echo "${OLD_FULL_VERSION}" | sed -e "s/${OLD_VERSUFFIX}\$//")


# Sanity checks
if [ -z "$(git tag -l "${OLD_FULL_VERSION}")" ]; then
    echo "Can not find tag for version ${OLD_FULL_VERSION} aborting ..."
    exit 1
fi

if [ "${FULL_VERSION}" = "${OLD_VERSION}" ]; then
    echo "New version must be different than old version!"
    exit 1
fi

# Computing dates

if echo "${VERSUFFIX}" | grep -qi '^rc'; then
    DATE="unpublished"
else
    DATE=$(date +"%Y-%m-%d")
fi
title="${FULL_VERSION} (${DATE})"
#shellcheck disable=SC2001
line=$(echo "${title}" | sed 's/./=/g')

echo "version ${FULL_VERSION} breaks into '${VERSION}' '${VERSUFFIX}' date ${DATE} from ${OLD_FULL_VERSION} (${OLD_VERSION} ${OLD_VERSUFFIX})"


# Cutting the Changelog into OLD and CURRENT
legacy="$(mktemp)"
current="$(mktemp)"

awk -e "BEGIN {show=0} /^${OLD_FULL_VERSION} \([0-9]{4}-[0-9]{2}-[0-9]{2}\)\$/ {show=1} {if (show==1) print; }" < CHANGELOG.rst > "${legacy}"
awk -e "/^${OLD_FULL_VERSION} \([0-9]{4}-[0-9]{2}-[0-9]{2}\)\$/ {nextfile} {print; }" < CHANGELOG.rst | awk -e '/^Statistics:$/ {nextfile} {print}' > "${current}"


# making sure the headings are right:

if [ "${VERSION}" = "${OLD_VERSION}" ]; then
    # releasing a golden release from RC, so we just change the version RC to the new one
    sed -i "${current}" \
        -e "/^${VERSION} (unpublished)$/a${title}" \
        -e "/^${VERSION} (unpublished)$/a${line}" \
        -e "/^${VERSION} (unpublished)$/,+1d" \
        -e "s/(unpublished)/(${DATE})/"
else

    # This is a first release (RC or equivalent),
    # let's add some headings to be sure we got all of them right for next steps
    sed -i "${current}" \
        -e "/^Unreleased$/a${title}" \
        -e "/^Unreleased$/a${line}" \
        -e "/^Unreleased$/a
" \
        -e "/^Unreleased$/aHighlights:" \
        -e "/^Unreleased$/a-----------" \
        -e "/^Unreleased$/,+1d" \
        -e "s/(unpublished)/(${DATE})/"
fi

# computing / updating each section

for scope in "${SCOPES[@]}"; do
    content=$(mktemp)
    heading="${SCOPES_HEADINGS[$scope]}"

    git log "${OLD_FULL_VERSION}.." --pretty="format:%s (%h) -- %aN" | grep -i "^${scope}:" | sed -e "s/^${scope}:/*/i" > "${content}"
    if [ -z "$(cat "${content}")" ]; then
        continue
    fi

    # making sure the heading is there:
    if ! grep -q "^${heading}\$" "${current}"; then
        # shellcheck disable=SC2129
        echo "${heading}" >> "${current}"
        # shellcheck disable=SC2001
        echo "${heading}" | sed -e 's/./-/g' >> "${current}"
        echo "" >> "${current}"
    fi

    sed -i "${current}" -e "/^${heading}\$/{N
r${content}
}"

   rm "${content}"
done

# generating statistics 

PR_NUMBER=$(git log --pretty=oneline "${OLD_FULL_VERSION}.." | wc -l)

cat >> "${current}" << EOF
Statistics:
-----------

This release includes ${PR_NUMBER} pull requests, and was created with the help of the following contributors (in alphabetical order):

EOF

while read -r name; do
    count=$( git log "${OLD_FULL_VERSION}.." --pretty=format:"%aN" | grep -c "${name}" )
    echo "* ${name} (${count} pull requests)" >> "${current}"
done < <( git log "${OLD_FULL_VERSION}.." --pretty=format:"%aN" | sort -u)

# shellcheck disable=SC2129
cat >> "${current}" << EOF

With the review help of the following contributors:

EOF

git log "${OLD_FULL_VERSION}.." | grep Co-authored-by | sed -e 's/^ *Co-authored-by: /* /;s/ <.*//' | sort -u >> "${current}"

cat >> "${current}" << EOF

Thanks to all contributors for their efforts!

EOF

cat "${current}" "${legacy}" > CHANGELOG.rst
rm "${current}" "${legacy}"

# now computing sections
