#!/bin/bash

set -e

SCRIPTS=$(dirname "$(realpath "$0")")
ROOT=$(git rev-parse --show-toplevel)

cd "${ROOT}/cms"

~/tx pull -f -t $TX_TOKEN
django-admin compilemessages

"${SCRIPTS}/filter-locale-changes"
