#!/bin/bash
SCRIPTS=$(dirname "$(realpath "$0")")
ROOT=$(git rev-parse --show-toplevel)

cd "${ROOT}/cms"

django-admin makemessages -l en --no-location
django-admin makemessages -l en -d djangojs --no-location

"${SCRIPTS}/filter-locale-changes"
echo tx push --source -l en --translation --token $TX_TOKEN
"${SCRIPTS}/tx" push --source -l en --translation --token $TX_TOKEN
echo Done.

