#!/bin/bash
SCRIPTS=$(dirname "$(realpath "$0")")
ROOT=$(git rev-parse --show-toplevel)

cd "${ROOT}/cms"

django-admin makemessages -l en --no-location
django-admin makemessages -l en -d djangojs --no-location

cd "${ROOT}"

"${SCRIPTS}/filter-locale-changes"
"${SCRIPTS}/tx" push  -l en -t

